variables:
  NODE_VERSION: "11.14"
  HELM_VERSION: "2.13.1"

stages:
  - setup
  - test
  - build
  - deploy

setup:api:
  stage: setup
  image: node:$NODE_VERSION
  before_script:
    - cd api/
  script:
    - npm install
    - npm run build
  variables:
    SUPPRESS_SUPPORT: "1"
  artifacts:
    paths:
      - api/dist/
      - api/node_modules/
    expire_in: 1 hour

setup:web:
  stage: setup
  image: node:$NODE_VERSION
  before_script:
    - cd web/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - web/build/
      - web/node_modules/
    expire_in: 1 hour

lint:api:
  stage: test
  image: node:$NODE_VERSION
  before_script:
    - cd api/
  script:
    - npm run lint

lint:web:
  stage: test
  image: node:$NODE_VERSION
  before_script:
    - cd web/
  script:
    - npm run lint

test:api:
  stage: test
  image: node:$NODE_VERSION
  before_script:
    - cd api/
  script:
    - npm run test

test:web:
  stage: test
  image: node:$NODE_VERSION
  before_script:
    - cd web/
  script:
    - npm run test

build:api:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - cd api/
    - echo "$GCR_API_KEY" | base64 -d | docker login --username _json_key --password-stdin https://eu.gcr.io
  script:
    - docker build -t eu.gcr.io/${GCP_PROJECT_ID}/bistrotime-api:${CI_COMMIT_SHA} .
    - docker push eu.gcr.io/${GCP_PROJECT_ID}/bistrotime-api:${CI_COMMIT_SHA}
  only:
    - master

build:web:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - cd web/
    - echo "$GCR_API_KEY" | base64 -d | docker login --username _json_key --password-stdin https://eu.gcr.io
    - echo "REACT_APP_MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}" > .env
    - echo "REACT_APP_BISTROTIME_API_URL=${BISTROTIME_API_URL}" > .env.production
  script:
    - docker build -t eu.gcr.io/${GCP_PROJECT_ID}/bistrotime-web:${CI_COMMIT_SHA} .
    - docker push eu.gcr.io/${GCP_PROJECT_ID}/bistrotime-web:${CI_COMMIT_SHA}
  only:
    - master

deploy:api:
  stage: deploy
  image:
    name: alpine/helm:$HELM_VERSION
    entrypoint: ["/bin/sh", "-c"]
  dependencies: []
  before_script:
    - mkdir ~/.kube
    - echo "$HELM_KUBECONFIG" | base64 -d > ~/.kube/config
    - helm init --client-only
    - helm version
  script:
    - helm upgrade
      --install bistrotime-api charts/bistrotime-api
      --namespace bistrotime
      --set image.tag=${CI_COMMIT_SHA}
  only:
    - master
