variables:
  NODE_VERSION: "11.14"
  HELM_VERSION: "2.13.1"
  DOCKER_REGISTRY: eu.gcr.io

stages:
  - setup
  - test
  - build
  - deploy
  - cleanup

.setup:
  stage: setup
  image: node:$NODE_VERSION
  script:
    - npm install
  artifacts:
    paths:
      - "*/node_modules"
    expire_in: 1 hour

setup:api:
  extends: .setup
  before_script:
    - cd api/
  variables:
    SUPPRESS_SUPPORT: "1"

setup:web:
  extends: .setup
  before_script:
    - cd web/

.lint:
  stage: test
  image: node:$NODE_VERSION
  script:
    - npm run lint

lint:api:
  extends: .lint
  before_script:
    - cd api/
  dependencies:
    - setup:api

lint:web:
  extends: .lint
  before_script:
    - cd web/
  dependencies:
    - setup:web

.test:
  stage: test
  image: node:$NODE_VERSION
  script:
    - npm run test

test:api:
  extends: .test
  before_script:
    - cd api/
  dependencies:
    - setup:api

test:web:
  extends: .test
  before_script:
    - cd web/
  dependencies:
    - setup:web

.build:
  stage: build
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - echo "$GCP_API_KEY" | base64 -d | docker login --username _json_key --password-stdin https://${DOCKER_REGISTRY}
  only:
    - master

build:api:
  extends: .build
  script:
    - cd api/
    - docker build -t ${DOCKER_REGISTRY}/${GCP_PROJECT_ID}/bistrotime-api:${CI_COMMIT_SHA} .
    - docker push ${DOCKER_REGISTRY}/${GCP_PROJECT_ID}/bistrotime-api:${CI_COMMIT_SHA}
  dependencies:
    - setup:api

build:web:
  extends: .build
  script:
    - cd web/
    - docker build -t ${DOCKER_REGISTRY}/${GCP_PROJECT_ID}/bistrotime-web:${CI_COMMIT_SHA} .
    - docker push ${DOCKER_REGISTRY}/${GCP_PROJECT_ID}/bistrotime-web:${CI_COMMIT_SHA}
  dependencies:
    - setup:web

.deploy:
  stage: deploy
  image:
    name: alpine/helm:$HELM_VERSION
    entrypoint: ["/bin/sh", "-c"]
  dependencies: []
  before_script:
    - mkdir ~/.kube
    - echo "$HELM_KUBECONFIG" | base64 -d > ~/.kube/config
    - helm init --client-only
    - helm version
  only:
    - master

deploy:api:
  extends: .deploy
  script:
    - helm upgrade
      --install bistrotime-api charts/bistrotime-api
      --namespace bistrotime
      --set image.tag=${CI_COMMIT_SHA}
      --set tokens.yelp=${YELP_TOKEN}
      --set tokens.citymapper=${CITYMAPPER_TOKEN}

cleanup:
  stage: cleanup
  image: google/cloud-sdk:alpine
  dependencies: []
  before_script:
    - echo "$GCP_API_KEY" | base64 -d > gcp-credentials.json
    - gcloud auth activate-service-account --key-file=gcp-credentials.json
  script:
    - ./bin/gcr-cleanup.sh ${DOCKER_REGISTRY}/${GCP_PROJECT_ID}/bistrotime-web 3
    - ./bin/gcr-cleanup.sh ${DOCKER_REGISTRY}/${GCP_PROJECT_ID}/bistrotime-api 3
  when: always
  only:
    - master
