{{- $fullName := include "bistrotime-web.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bistrotime-web.name" . }}
    helm.sh/chart: {{ include "bistrotime-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
    {{- range .Values.hosts }}
      - {{ . | quote }}
    {{- end }}
      secretName: {{ .Release.Name }}-tls
  rules:
  {{- range .Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
