apiVersion: v1
kind: Service
metadata:
  name: {{ include "bistrotime-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bistrotime-web.name" . }}
    helm.sh/chart: {{ include "bistrotime-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "bistrotime-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
