apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "bistrotime-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bistrotime-api.name" . }}
    helm.sh/chart: {{ include "bistrotime-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ . | quote }}
  {{- end }}
  secretName: {{ .Chart.Name }}-tls
  issuerRef:
    name: letsencrypt
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
        {{- range .Values.ingress.hosts }}
          - {{ . | quote }}
        {{- end }}
