apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bistrotime-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bistrotime-api.name" . }}
    helm.sh/chart: {{ include "bistrotime-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bistrotime-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bistrotime-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: CITYMAPPER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "bistrotime-api.fullname" . }}
                  key: citymapper_token
            - name: YELP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "bistrotime-api.fullname" . }}
                  key: yelp_token
          ports:
            - name: http-alt
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /platform/ping
              port: http-alt
          readinessProbe:
            httpGet:
              path: /platform/ping
              port: http-alt
