apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bistrotime-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bistrotime-api.name" . }}
    helm.sh/chart: {{ include "bistrotime-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  yelp_token: {{ .Values.tokens.yelp | b64enc | quote }}
  navitia_token: {{ .Values.tokens.navitia | b64enc | quote }}
